import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
  SignIn,
  useUser,
} from "@clerk/nextjs";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Tuber",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <header className="flex justify-between">
            <SignedIn>
              <div className="user absolute top-0 right-0 p-4 ">
                <UserButton />
              </div>
            </SignedIn>
          </header>
          <main>
            {/* <Navbar /> */}
            <SignedIn>{children}</SignedIn>
            <SignedOut>
              <div className="flex items-center justify-center h-screen">
                <SignIn routing="hash" />
              </div>
            </SignedOut>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
