import GoogleMapSection from "@/components/Home/GoogleMapSection";
import SearchSection from "@/components/Home/SearchSection";
import InputBox from "@/components/Home/InputBox";

export default function Home() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
      <div className="search ml-3">
        <SearchSection />
        <InputBox type="source" />
        <InputBox type="destination" />
        <div className="inputsdateandtime">
          <input
            type="date"
            placeholder="Today"
            className="px-3 ml-7 mt-3 py-2 border bg-gray-100 rounded-lg outline-none "
          />{" "}
        </div>
        <button className="bg-black w-full p-3 text-white rounded-2xl mt-5 ml-3">
          Search
        </button>
      </div>
      <div className="googlemap col-span-2 ">
        <GoogleMapSection />
      </div>
    </div>
  );
}

export const metadata = {
  title: "Hoppr",
  description: "Generated by create next app",
};
